FROM node:10 as frontend

WORKDIR /home/node/app/

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
RUN npm install

COPY ./ ./

RUN npm run prod

RUN ./node_modules/.bin/apidoc -i ./src/api/ -o ./docs/rest_api/dist/

RUN npm prune --production


FROM nginx:1.13

WORKDIR /var/www/app/

COPY --from=frontend /home/node/app/ ./

COPY ./docker/config/nginx/sites/ /etc/nginx/conf.d/
